### ISSUE TITLE
Manchester pattern

### ISSUE THREAD

**Issue by ashiq1213** [LieBtrau/arduino-as3933#1] opened 2016-08-26 17:45 UTC
I want to generate 125Khz signal with manchester pattern. I tried using this library but couldn't find the output in CRO.

**Comment by LieBtrau** [comment] 2016-08-28 13:20
Hi Ashiq1213,
This library has been designed for Adafruit Protrinket 3V.  With small modifications it should work for any ATMEGA328 board (such as Arduino Uno).  Unfortunately I don't have an Uno right now, so I can't test it.
If you want this code to work for Arduino Uno, you should:
- change the "#ifdef ARDUINO_AVR_PROTRINKET3" to "#ifdef ARDUINO_AVR_PROTRINKET3 || defined(ARDUINO_AVR_UNO)" (without the " s)
- The pwm output is on pin 10
- An arduino Uno works on 16MHz, a Adafruit Protrinket3V works on 12MHz.  The values for OCR1A and OCR1B should be changed accordingly. OCR1A=127, OCR1B=63.

I'll try to get an Arduino Uno to make the changes and test them.

**Comment by ashiq1213** [comment] 2016-08-28 13:26
thank you for your kind reply. I will change the code as per your guidance
mean while it would be great if you too test it and give me a confident
result.

Best regards,
Ashiq

**Comment by ashiq1213** [comment] 2016-08-29 14:57
Hi LieBtrau, I tried the following example code. It got compiled and uploaded but i couldn't see any output in CRO.
//Includes for libraries must be done in *.ino file
#include "SPI.h"

//Includes needed for this file
#include ''as3933gen.h''
//#include <as3933.h>
#include ''RingBuffer.h''
byte pattern[]={0x127, 0x63};
As3933Gen as(pattern);

// the setup function runs once when you press reset or power the board
void setup()
{
    pinMode(11, OUTPUT);
    as.begin();
}

// the loop function runs over and over again forever
void loop()
{
//    if(!as.isBusy())
//    {
//        as.generate(a);
//        bitClear(PORTB,PB3);
//    }
}

**Comment by ashiq1213** [comment] 2016-08-30 16:35
Hi LieBtrau,
could you give an example for using as3933.h library. I feel something missing in constructor of as3933.cpp file.

**Comment by LieBtrau** [comment] 2016-08-30 20:30
Hi Ashiq,
I fixed the wave form generation: as3933gen.  The solution is on the task branch.  The example "test2" shows you how to use it to generate a waveform.  I tested it on Protrinket 3V.  I have an Uno now, so I can test it on that one too if I find some time. Waveform output is on pin 10.
BTW: The pattern for the AS3933 generator expects two bytes: 0x127 is already two bytes: 0x01 and 0x27.  Didn't you get a compiler warning on that one?

About controlling the AS3933:
I'll try to have a look at the as3933 later to see what's wrong there.

**Comment by ashiq1213** [comment] 2016-08-30 21:47
Hi LieBtrau,

many more thanks for the necessary changes. for as3933 I gave byte pattern
as (0×96,0×69). I dint get any warning from compiler.

It would be great if you give an example for as3933.

**Comment by ashiq1213** [comment] 2016-08-31 08:15
Hi LieBtrau,
             example you have given for as3933gen is working great, Cheers! In as3933 library am trying to set the correlator and write data but am getting error in scope. I feel something is missing in constructor. could you check it and add a suitable example.

**Comment by LieBtrau** [comment] 2016-08-31 20:30
Hi Ashiq,
On the " tsk_as3933_example_fix"-branch you can find the "test1"-example that compiles, but is not functional.  The constructor is called with three parameters: SPI object, the SS-pin (connected to pin 1 of the AS3933), and the DAT-pin (connected to pin 15 of the AS3933).
The problem is that my self-made hardware doesn't work correctly.  I can only calibrate one antenna.  This makes it hard to debug my code.  Buying the dev kit is not an option for me, because I find it much too expensive.
Later I'll try to write the antenna calibration functionality, but I can only test it with one antenna.

**Comment by ashiq1213** [comment] 2016-08-31 20:52
Hi liebtrau,

thanks for your support. you said this example is not functional. then how
do we enable the correlator of As3933. I need an example to enable the
correlator. According to datasheet, we need to assign value 1 to R1<1> in
order to enable correlator. how do we do that?

**Comment by LieBtrau** [comment] 2016-09-01 07:06
Hi Ashiq,
I'd like to know what hardware you're using for the AS3933.  Could you send me your schematic?
The circuit that I designed for this can be found on: [3D LF wakeup receiver](https://workspace.circuitmaker.com/Projects/Details/christoph-tack-2/3D-LF-wakeup-receiver-evaluation).

**Comment by ashiq1213** [comment] 2016-09-01 08:27
Hi liebtrau,
I have attached the pic of the schematic. could you help me in enabling the
correlator. either using your library or making a separate coding to enable
it. because I have already coded to transmit data in serial mode and made
microcontroller to wait for interrupt by putting microcontroller in power
down mode. now I need to enable the correlator and merge that with my
coding.

**Comment by LieBtrau** [comment] 2016-09-01 08:37
Where is the attachment?

Anyway, before you can set the correlator, you'll first need to tune the antenna and calibrate the RC-oscillator.  I'm writing that code now.

**Comment by ashiq1213** [comment] 2016-09-01 08:51
![pcb detail](https://cloud.githubusercontent.com/assets/21266519/18161346/d7e88562-7031-11e6-8e27-d83e17f26d06.jpg)

some problem with attached pic. I have re attached now is it visible?

**Comment by ashiq1213** [comment] 2016-09-01 09:16
Hi liebtrau, I am using the code below to transmit data in serial mode and made
microcontroller to wait for interrupt by putting microcontroller in power
down mode. Now i need to attach a code to enable correlator.

#include <avr/sleep.h>
void setup() {
  // start serial port at 9600 bps:
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  Serial.begin(9600);     //start serial communication at 9600 baud
    pinMode(13,OUTPUT);     // set pin 13 as an output so we can use LED to monitor
    digitalWrite(13,LOW);   // turn pin 13 LED off
    pinMode(2, INPUT);      //Set interrupt pin 2 as input
    digitalWrite(2,LOW);   //activate the internal pull-up resistor to pull it high when jumper is not connected to GND
  establishContact();  // send a byte to establish contact until receiver responds
   pinMode(10, INPUT);//wake(implement pull-down resistance)
   pinMode(8, OUTPUT);//10-pin output
   pinMode(12, OUTPUT);//ss-chip select
}

void loop() {
  // if we get a valid byte, read analog ins:
  //delay(5000);  // Stay awake for 5 seconds, then sleep. These are the 5 seconds when we see ~40mA on the multimeter.
    sleepSetup();   //now we see ~27 mA until pin 2 is connected to GND
  digitalWrite(12, HIGH);
  //if (Serial.available() > 0) {

}

void establishContact() {
  while (Serial.available() <= 0) {
    //Serial.print(11010000);   // send a capital A
    Serial.write(11010000);
    delay(300);
    Serial.write(11111111);
    delay(5000);
    sleepSetup();
    //delay(300);
  }
}
void sleepSetup()
{
    sleep_enable();
    attachInterrupt(0, pinInterrupt, HIGH);//Set pin 2 as interrupt and attach Interrupt Service Routine (ISR)
    set_sleep_mode(SLEEP_MODE_PWR_DOWN);//define power down sleep mode
    digitalWrite(13,LOW);   // turn LED off to indicate sleep
    sleep_cpu();//Set sleep enable (SE) bit, this puts the ATmega to sleep
    Serial.println("just woke up!");//When it wakes up due to the interrupt the program continues with the instruction following sleep_cpu() 
    digitalWrite(13,HIGH);   // turn LED on to indicate wake up
}

void pinInterrupt()//ISR
{
  sleep_disable();
  detachInterrupt(0);

}

**Comment by LieBtrau** [comment] 2016-09-01 10:05
Hi Ashiq,  let's do this step by step.  So that we have a strong base to build on and add extra functionality.
On the task branch, I added code that tunes the LF1P antenna (the only one you're using).  The tuned antenna is then used to calibrate the internal oscillator.  This works on my hardware.  I suggest you try it too.  This code checks your SPI bus, tuning circuit and antenna connection.
Once you've got that working, we can move on to the next step.

**Comment by ashiq1213** [comment] 2016-09-01 10:31
Hi LieBtrau, am getting the following error:
''fatal error: FreqCount.h: No such file or directory,
 #include "FreqCount.h''

Can i add any freqcount library to this library or i should add specific library you used for freqcount

**Comment by LieBtrau** [comment] 2016-09-01 10:56
You'll have to change your pin usage.  See as3933.h.  Pins 10-13 have to be used for SPI.  Pin 5 is needed for the antenna calibration.

**Comment by ashiq1213** [comment] 2016-09-01 11:05
I have done the spi connections. I am getting the about stated error ''fatal error: FreqCount.h: No such file or directory,
#include "FreqCount.h''
Can i add any freqcount library to this library or i should add specific library you used for freqcount?

**Comment by LieBtrau** [comment] 2016-09-01 11:34
[FreqCount library on GitHub](https://github.com/PaulStoffregen/FreqCount)

**Comment by ashiq1213** [comment] 2016-09-01 11:50
code got compiled and i saw the following result in serial monitor:
''test1: Checking AS3933 functionality
Communication with AS3933 fails.
Tuning antenna : LF1
Testing bit: 4
    Frequency: 0
Testing bit: 3
    Frequency: 0
Testing bit: 2
    Frequency: 0
Testing bit: 1
    Frequency: 0
Testing bit: 0
    Frequency: 0
Calibration for antenna 1 fails''

**Comment by LieBtrau** [comment] 2016-09-01 14:11
I pushed a new version on the task branch that gives more debug info when communication fails.

**Comment by ashiq1213** [comment] 2016-09-01 16:09
code got compiled and i saw the following result in serial monitor:
test1: Checking AS3933 functionality
Reading data from AS3933 fails: 
r5: 0
r6: 0
Communication with AS3933 fails.

**Comment by ashiq1213** [comment] 2016-09-01 16:14
while running the updated example, I removed ground between IC and Uno board. then i got values in r5andr6.

''test1: Checking AS3933 functionality
Reading data from AS3933 fails: 
r5: FF
r6: FF
Communication with AS3933 fails.''

**Comment by LieBtrau** [comment] 2016-09-01 19:17
Your AS3933 doesn't communicate at all.  You should get 0X69 and 0X96 for r5 and r6.  
Check all the connections again and pin voltages  (3.6V MAX).  If this first step doesn't work, it's no use going further.

**Comment by ashiq1213** [comment] 2016-09-01 19:46
thank you christoph. I will try again if there is any error with pins or code any.

**Comment by ashiq1213** [comment] 2016-09-01 20:17
If i give battery power to As3933, am getting output as r5=0,r6=0
If i give power supply to As3933 from uno board(3.3v), am getting output as r5=FF,r6=FF.
I made two boards, I tried on both and getting same output.
Is there any other way to enable correlator.
I have planned to use As3933gen library to transmit wired signal with signal generator to the antenna connector. So i want to enable the correlator to detect the manchester pattern of the transmitting signal.

**Comment by LieBtrau** [comment] 2016-09-02 06:39
To be able to enable the correlator, you need to be able to communicate to the AS3933.  As long as you don't have that one fixed, there's nothing you can do with the AS3933.
If you send me your schematic, maybe I could help you out.
Remark that the IO voltages of the Arduino Uno are 5V.  You'll need level translators between the Uno and the AS3933 for the SPI.  If you didn't do this, you've probably fried the AS3933 already.
If you use a 3V3 Arduino type (ProTrinket3V, Arduino Pro 3V, Arduino Pro Mini 3V), you don't need level shifting.

**Comment by ashiq1213** [comment] 2016-09-02 07:30
do you want my gerber file for schematic or hand sketch.
but As3933 worked in serial transmission. I made a code to serialy transmit
a data from Uno to As3933. after transmitting data I put my uno in power
down mode and made it wait for interrupt. once I gave interrupt from
14pin(wake) of As3933 to Uno, it woke up from power down mode.

**Comment by LieBtrau** [comment] 2016-09-02 09:18
For making the gerber file, you should have drawn a schematic first.  The schematic is what I want, not the gerber file.  What program are you using to do the PCB layout? Eagle, Altium?

What do you mean by "As3933 worked in serial transmission"?  The AS3933 is an RX-only IC.

**Comment by ashiq1213** [comment] 2016-09-02 14:15
[PCB1 LEGEND.pdf](https://github.com/LieBtrau/arduino-as3933/files/452162/PCB1.LEGEND.pdf)
Hi christoph, I have uploaded schematic pdf. I used EASY PC software for PCB layout.

sorry i did a wrong test. AS3933 is Receiver only.

**Comment by LieBtrau** [comment] 2016-09-02 17:13
Ashiq, this is not a schematic.  It's an assembly drawing.  I need the "schematic capture" as your Easy-PC software calls it.  Did you make a schematic?  You mentioned a hand-sketch already.  That would do if you didn't make a schematic.
In case you didn't make a schematic: I strongly suggest you use schematics in the future and export them to the PCB-layout.  It excludes many types of connection errors.

**Comment by ashiq1213** [comment] 2016-09-02 18:09
Christoph, I had schematic capture but that pdf is missing. Am trying to
retrieve it. thank you for your support.

**Comment by ashiq1213** [comment] 2016-09-02 19:31
christoph, can you give me a separate code to enable correlator (R1<1>=0)
without calling it from  As3933 library. just to give a try, while testing
if something happens then it will be great.

**Comment by LieBtrau** [comment] 2016-09-02 19:36
Don't count on it.
As long as you get "Communication with AS3933 fails." it will never work.
You want to run before you can walk.  I'm willing to help, but you have to be reasonable.

**Comment by ashiq1213** [comment] 2016-09-02 19:38
yes your right. I wil try to fix it. thank you so much.

**Comment by LieBtrau** [comment] 2016-09-04 10:23
Correlator has now also been implemented.
If all goes well, you should see this on startup:

> test1: Checking AS3933 functionality
> Tuning antenna : LF1
> Testing bit: 4
>         Frequency: 127541
> Testing bit: 3
>         Frequency: 125328
> Testing bit: 2
>         Frequency: 124255
> Testing bit: 1
>         Frequency: 124785
> Testing bit: 0
>         Frequency: 125058
> RC-oscillator OK
> Everything set up.

**Comment by ashiq1213** [comment] 2016-09-04 10:50
thank you christoph. I will try this one.

**Comment by ashiq1213** [comment] 2016-09-04 11:06
Christoph, I just added the library to arduino and the i compiled the new example and uploaded on UNO board. I got the same output: 
test1: Checking AS3933 functionality
Reading data from AS3933 fails: 
r5: 0
r6: 0
Communication with AS3933 fails.
Should I make any changes in example program before i upload in UNO board.

**Comment by LieBtrau** [comment] 2016-09-04 11:25
No, you have to make changes to your hardware.  Your SPI communication doesn't work.  Check all the connections again.  You could also connect a logic analyzer to the SPI bus.

**Comment by ashiq1213** [comment] 2016-09-04 12:11
I need to order an logic analyzer to check and also am trying to get an protrinket 3v. I am planning to Remake the hardware design. but in my hardware am getting output from groung pin(pin6) and supply pin(pin5).
Which software you used for PCB layout?
How is your hardware? what are the goals like sensitivity,power consumption,wakeup range you reached with your hardware?

**Comment by LieBtrau** [comment] 2016-09-04 15:10
Hi Ashiq, I made the design with CircuitMaker.  The designs are stored online.  The design of my hardware can be found [here](http://workspace.circuitmaker.com/Projects/Details/christoph-tack-2/3D-LF-wakeup-receiver-evaluation).  This design isn't perfect: see the comments.  
To be honest, I stopped development on this AS3933 project.  I'm using a Bluetooth Low Energy module (RN4020) now.  It provides much more functionality than the AS3933, it's smaller, it can communicate with smartphones, it provides two way communication (also encrypted), the range can be adjusted by changing TX-power, no high power TX-station is needed.  The power consumption is in the 10uA range if you set it up well.  So it can live a few years on a coin cell.  The hardware is much simpler to implement too.

**Comment by ashiq1213** [comment] 2016-09-04 15:31
great. all the best

**Comment by ashiq1213** [comment] 2016-09-05 09:50
hi christoph, I have ordered for pro trinket 3v. what board you selected in
tools menu to use pro trinket in arduino software? and if am using Pro
trinket, which library and what examples should I use?
In task branch, example test 2 why have you given pattern as 12 and 34. the
required pattern is 96 and 69 right?

**Comment by LieBtrau** [comment] 2016-09-05 17:08
Hi Ashiq, I'm using an FTDI cable to program the ProTrinket.  Adafruit has an excellent guide about the ProTrinket.  Start with a simple "blinky" or something like that.
You can use example/test1 and example/test2 as is.

Example test2 and test1 both use 0x12 and 0x34.  The default pattern for AS3933 is indeed 0x96 and 0x69, but the exampe/test2 overwrites it.

**Comment by ashiq1213** [comment] 2016-09-05 18:49
thank you christoph.

**Comment by ashiq1213** [comment] 2016-09-07 13:43
christoph, I am trying to upload the code in Protrinket but am getting error message as "Could not find USBtiny device (0x2341/0x49)". since am using windows, I installed drivers and selected the board in tools but getting the same error. Did you face this problem?

**Comment by LieBtrau** [comment] 2016-09-07 18:24
Hi Ashiq, we're going way out of topic here.  
I'm using Ubuntu.  No problems here.  
If you follow [this Adafruit guide](https://cdn-learn.adafruit.com/downloads/pdf/adafruit-arduino-ide-setup.pdf) it will probably solve your problem.
[This guide](https://cdn-learn.adafruit.com/downloads/pdf/introducing-pro-trinket.pdf) covers ProT rinket setup specifically.
Be sure to install the windows driver.  You could check your "Device Manager" in Windows to see if your ProTrinket3V is correctly detected.

**Comment by ashiq1213** [comment] 2016-09-07 18:57
thank you christoph. I will try

**Comment by ashiq1213** [comment] 2016-09-09 10:16
Hi christoph,
[CIRCUIT - Schematic.pdf](https://github.com/LieBtrau/arduino-as3933/files/463745/CIRCUIT.-.Schematic.pdf)
This is my schematic.

**Comment by LieBtrau** [comment] 2016-09-09 17:51
Your schematic is strange.  It looks like you've connected an AM-radio detector to your board.  You'll probably want to connect a long wire on the left, where the 2pF is connected.  I'm not a radio expert, but I think a magnetic loop antenna works better than a long wire for LF.
You're using the AS3933 in a way that it was not designed for.  There's a lot of special functionality in it, that you won't use, but you will pay for it.  Is the AS3933 the right part for you?

I guess this design is your solution to solve some kind of problem.  What is the initial problem?  What will you use this for?

**Comment by ashiq1213** [comment] 2016-09-09 18:01
this is my thesis. I jus want AS3933 to detect 125kHz signal and give an
interrupt to microcontroller to make it awake from sleep mode. I am using
868MHz indoor antenna to receive the signal and it is followed by impedance
matching and Envelope detector to As3933. I tried giving 125Khz signal to
9th pin of As3933 and check the output of wake pin in oscilloscope. It gave
some negative spikes with pulse. And using interrupt program I realized am
getting 0 as output from wake pin.
I will try to redo my schematic and hardware.

**Comment by LieBtrau** [comment] 2016-09-10 07:48
So you're AM-modulating a 125KHz waveform onto an 868MHz carrier?  I haven't seen AM-modulation on that frequency.  Most modules uses some kind of FM.  There must be a reason for that.
Do you already have hardware to do that?  I hope so, otherwise you won't be able to test your AS3933 circuit.
I suggest you then build your receiver circuit (disconnecting the AS3933 on pin 9) and check what waveform you're receiving.  If the demodulated waveform looks ok, then you can hook up the AS3933 to it and start debugging.

**Comment by ashiq1213** [comment] 2016-09-10 10:49
Am using an signal generator for modulation. I read from a research paper
with this kind of testing. And this As3933 also has a feature of going to
receiving mode without pattern detection. Am trying to figure out how to
check this As3933 working without pattern detection.

**Comment by LieBtrau** [comment] 2016-09-10 18:31
Hi Ashiq,

If you experience problems with the library, let me know in a new issue.  Almost all functionality of the AS3933 is covered now. e.g. "receiving mode without pattern detection": setWakeUpProtocol(As3933::WK_FREQ_DET_ONLY)

I'll close this issue, because your initial problem "can't create manchester code output" has been solved.

We went way out of topic with this issue.  I won't make this a habit.  You should ask guidance from your thesis promotor.  If you have problems not concerning this library, I'll close them as being irrelevant.

**Closed as completed by LieBtrau** 2016-09-10 18:31 UTC

**Comment by ashiq1213** [comment] 2016-09-10 18:38
thank you for your library
